=== ngodfraind/json-quiz/format/quiz/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "meta": {
      "allOf": [
        {
          "$ref": "http://json-quiz.github.io/json-quiz/schemas/metadata/schema.json"
        }
      ]
    },
    "parameters": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "enum": ["formative", "evaluative", "summative"],
              "description": "Hide the name of the users who have passed the quiz in the results",
              "default": "summative"
            },
            "anonymizeAttempts": {
              "type": "boolean",
              "description": "Hide the name of the users who have passed the quiz in the results",
              "default": false
            },
            "interruptible": {
              "type": "boolean",
              "description": "Is it possible to stop the quiz and continue it later ?",
              "default": false
            },
            "duration": {
              "type": "number",
              "minimum": 0,
              "description": "The allowed duration to pass the quiz",
              "default": 0
            },
            "maxAttempts": {
              "type": "number",
              "minimum": 0,
              "description": "The number of times a user can pass the quiz. If 0, there is no limit",
              "default": 0
            },
            "maxAttemptsPerDay": {
              "type": "number",
              "minimum": 0,
              "description": "The number of times a user can pass the quiz per day. If 0, there is no limit. It is limited by max Attemps",
              "default": 0
            },
            "maxPapers": {
              "type": "number",
              "minimum": 0,
              "description": "The maximum amount of paper a quizz can have. If 0, there is no limit.",
              "default": 0
            },
            "showOverview": {
              "type": "boolean",
              "description": "Show overview to users or directly start the quiz if false",
              "default": true
            },
            "showEndPage": {
              "type": "boolean",
              "description": "Display an end page when the user has finished the quiz",
              "default": false
            },
            "endMessage": {
              "type": "string",
              "description": "A message to display at the end of the quiz",
              "default": null
            },
            "showMetadata": {
              "type": "boolean",
              "description": "Display detail information about the exercise",
              "default": true
            },
            "showStatistics": {
              "type": "boolean",
              "description": "Display statistics about what users have answered",
              "default": false
            },
            "showFullCorrection": {
              "type": "boolean",
              "description": "Display the full correction with expected answers",
              "default": true
            },
            "showCorrectionAt": {
              "enum": ["validation", "lastAttempt", "date", "never"],
              "description": "The point at which users can view the correction of their attempt to the quiz",
              "default": "validation"
            },
            "showScoreAt": {
              "enum": ["validation", "correction", "never"],
              "description": "The point at which users can view the score of their attempt to the quiz",
              "default": "correction"
            },
            "showFeedback": {
              "type": "boolean",
              "description": "Display immediate feedback about his answer to the user",
              "default": false
            },
            "totalScoreOn": {
              "type": "number",
              "minimum": 0,
              "description": "If this value is greater than 0 we should compute the score based on the value, else it will be computed based on the sum of all questions score",
              "default": 0
            },
            "numbering": {
              "enum": ["none", "litteral", "numeric"],
              "description": "The question numbering",
              "default": "none"
            },
            "mandatoryQuestions": {
              "type": "boolean",
              "default": false,
              "description": "It is mandatory to answer the questions to continue the quizz"
            }
          }
        },
        {
          "oneOf": [
            {
              "type": "object",
              "properties": {
                "randomOrder": {
                  "enum": ["once", "never", "always"],
                  "description": "Randomize order of steps in the quiz",
                  "default": "never"
                },
                "randomPick": {
                  "enum": ["once", "never", "always"],
                  "description": "Pick a random sub set of steps in the quiz",
                  "default": "never"
                },
                "pick": {
                  "type": "number",
                  "minimum": 0,
                  "description": "Number of steps to use when a user pass the quiz. If 0, all the steps are used",
                  "default": 0
                }
              }
            },
            {
              "type": "object",
              "properties": {
                "randomTags": {
                  "type": "object",
                  "properties": {
                    "pick": {
                      "type": "array",
                      "items": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "integer"
                        }
                      ]
                    },
                    "pageSize": {
                      "type": "integer",
                      "description": "The number of question per pages"
                    }
                  },
                  "required": ["randomTags", "pageSize"]
                }
              },
              "required": ["randomTags"]
            }
          ]
        }
      ]
    },
    "steps": {
      "type": "array",
      "uniqueItems": true,
      "items": { "$ref": "http://json-quiz.github.io/json-quiz/schemas/step/schema.json" }
    }
  },
  "required": ["id", "title", "steps"]
}

=== ngodfraind/json-quiz/format/quiz/examples/valid/with-tag-picking.json
{
  "id": "1",
  "title": "quiz title",
  "meta": {
    "authors": [
      {
        "name": "John Doe",
        "email": "john@mail.com"
      }
    ],
    "created": "2015-06-04",
    "license": "CC"
  },
  "parameters": {
    "type": "summative",
    "anonymizeAttempts": false,
    "interruptible": true,
    "duration": 0,
    "maxAttempts": 5,
    "randomOrder": "once",
    "randomPick": "never",
    "pick": 0,
    "showOverview": true,
    "showEndPage": true,
    "showMetadata": true,
    "showStatistics": false,
    "showFullCorrection": true,
    "showCorrectionAt": "validation",
    "showScoreAt": "correction",
    "showFeedback": true,
    "totalScoreOn": 0,
    "randomTags": {
      "pick": [["tag1", 2], ["tag2", 3]],
      "pageSize": 3
    }
  },
  "steps": [
    {
      "id": "1",
      "items": [
        {
          "id": "1",
          "content": "Question ?",
          "type": "application/x.choice+json",
          "choices": [
            {
              "id": "1",
              "type": "image/png",
              "url": "http://domain.com/image-1.png"
            },
            {
              "id": "2",
              "type": "image/png",
              "data": "http://domain.com/image-2.png"
            },
            {
              "id": "3",
              "type": "image/png",
              "data": "http://domain.com/image-3.png"
            }
          ],
          "random": true,
          "multiple": true
        }
      ]
    }
  ]
}
